ZSFGH_f<-read.csv("ZSFGH_f.csv", header = TRUE)
str(ZSFGH_f)

data_procedure <-read.csv("procedure_raw.csv",header = TRUE)

str(data_procedure)
colnames(data_procedure)
names(data_procedure) <- c("MRN","PtNo","Total.Procedures")
ZSFGH_h <-left_join(ZSFGH_f, data_procedure, by= c("PtNo","MRN"))
str(ZSFGH_h)
View(ZSFGH_h)
View(data_procedure)
summary(ZSFGH_h)
nrow(ZSFGH_h)
nrow(ZSFGH_b)
